defmodule MishkaGervaz.Form.Types.FieldTest do
  @moduledoc """
  Tests for the form field type registry generated by
  `MishkaGervaz.Table.Behaviours.TypeRegistry`.

  Covers `get/1`, `get_or_passthrough/1`, `builtin?/1`, `builtin_types/0`,
  `default/0`, and `infer_from_ash_type/1`.
  """
  use ExUnit.Case, async: true

  alias MishkaGervaz.Form.Types.Field, as: Registry

  describe "get/1" do
    test "returns the module for built-in atoms" do
      assert Registry.get(:text) == MishkaGervaz.Form.Types.Field.Text
      assert Registry.get(:textarea) == MishkaGervaz.Form.Types.Field.Textarea
      assert Registry.get(:relation) == MishkaGervaz.Form.Types.Field.Relation
      assert Registry.get(:json) == MishkaGervaz.Form.Types.Field.Json
      assert Registry.get(:password) == MishkaGervaz.Form.Types.Field.Password
    end

    test "returns nil for unknown atoms" do
      assert Registry.get(:not_a_real_type) == nil
    end
  end

  describe "get_or_passthrough/1" do
    test "returns the module for built-in atoms" do
      assert Registry.get_or_passthrough(:text) == MishkaGervaz.Form.Types.Field.Text
    end

    test "passes unknown atoms through (so custom modules work via `field :foo, MyMod`)" do
      assert Registry.get_or_passthrough(:not_a_real_type) == :not_a_real_type
      assert Registry.get_or_passthrough(MyApp.CustomFieldType) == MyApp.CustomFieldType
    end
  end

  describe "builtin?/1" do
    test "true for registered atoms" do
      assert Registry.builtin?(:text)
      assert Registry.builtin?(:relation)
      assert Registry.builtin?(:nested)
    end

    test "false for unknown atoms" do
      refute Registry.builtin?(:not_a_real_type)
    end
  end

  describe "builtin_types/0" do
    test "lists all registered type names" do
      types = Registry.builtin_types()

      assert :text in types
      assert :textarea in types
      assert :password in types
      assert :select in types
      assert :multi_select in types
      assert :checkbox in types
      assert :toggle in types
      assert :date in types
      assert :datetime in types
      assert :number in types
      assert :range in types
      assert :json in types
      assert :hidden in types
      assert :file in types
      assert :upload in types
      assert :combobox in types
      assert :relation in types
      assert :nested in types
      assert :array_of_maps in types
      assert :string_list in types
    end
  end

  describe "default/0" do
    test "returns Field.Text" do
      assert Registry.default() == MishkaGervaz.Form.Types.Field.Text
    end
  end

  describe "infer_from_ash_type/1" do
    test "returns default for nil" do
      assert Registry.infer_from_ash_type(nil) == Registry.default()
    end

    test "Ash.Type.String → Field.Text" do
      assert Registry.infer_from_ash_type(%{type: Ash.Type.String}) ==
               MishkaGervaz.Form.Types.Field.Text
    end

    test "Ash.Type.Boolean → Field.Checkbox" do
      assert Registry.infer_from_ash_type(%{type: Ash.Type.Boolean}) ==
               MishkaGervaz.Form.Types.Field.Checkbox
    end

    test "Ash.Type.Integer / Float / Decimal → Field.Number" do
      assert Registry.infer_from_ash_type(%{type: Ash.Type.Integer}) ==
               MishkaGervaz.Form.Types.Field.Number

      assert Registry.infer_from_ash_type(%{type: Ash.Type.Float}) ==
               MishkaGervaz.Form.Types.Field.Number

      assert Registry.infer_from_ash_type(%{type: Ash.Type.Decimal}) ==
               MishkaGervaz.Form.Types.Field.Number
    end

    test "Ash.Type.Date → Field.Date" do
      assert Registry.infer_from_ash_type(%{type: Ash.Type.Date}) ==
               MishkaGervaz.Form.Types.Field.Date
    end

    test "DateTime variants → Field.DateTime" do
      assert Registry.infer_from_ash_type(%{type: Ash.Type.DateTime}) ==
               MishkaGervaz.Form.Types.Field.DateTime

      assert Registry.infer_from_ash_type(%{type: Ash.Type.UtcDatetime}) ==
               MishkaGervaz.Form.Types.Field.DateTime

      assert Registry.infer_from_ash_type(%{type: Ash.Type.UtcDatetimeUsec}) ==
               MishkaGervaz.Form.Types.Field.DateTime
    end

    test "Ash.Type.Map → Field.Json" do
      assert Registry.infer_from_ash_type(%{type: Ash.Type.Map}) ==
               MishkaGervaz.Form.Types.Field.Json
    end

    test "unknown type → default" do
      assert Registry.infer_from_ash_type(%{type: :wibble}) == Registry.default()
    end
  end
end
